### ISSUE TITLE
Exception: An empty graph encountered!

### ISSUE THREAD

**Issue by mohsen-goodarzi** [YiwenShaoStephen/pychain_example#5]
I am trying to prepare an example using mini_libripeech corpus.
In stage 5(model training), I get the following exception: 

```
Stage 5: Model Training
Namespace(arch='TDNN', beta1=0.9, beta2=0.999, bidirectional=False, curriculum=1, den_fst='data/graph/monophone/normalization.fst', dilations=[1, 1, 3, 3, 3], dropout=0.2, epochs=20, exp='exp/tdnn_monophone', feat_dim=40, gamma=0.5, hidden_dims=[384, 384, 384, 384, 384], kernel_sizes=[3, 3, 3, 3, 3], layers=5, lr=0.001, milestones=[5, 10], momentum=0.9, num_targets=82, optimizer='adam', print_freq=10, resume='', scheduler='plateau', seed=1, start_epoch=0, strides=[1, 1, 1, 1, 3], train='data/train_monophone.json', train_bsz=128, valid='data/valid_monophone.json', valid_bsz=128, weight_decay=0.01)
Saving model and logs to exp/tdnn_monophone
Initializing dataset...
100%|██████████| 1519/1519 [00:00<00:00, 3313.59it/s]
Initializing dataset...
  0%|          | 0/1089 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/textmining/Goodarzi/pychain_example/examples/mini_librispeech/../../train.py", line 318, in <module>
    main()
  File "/home/textmining/Goodarzi/pychain_example/examples/mini_librispeech/../../train.py", line 118, in main
    validset = ChainDataset(args.valid)
  File "/home/textmining/Goodarzi/pychain_example/dataset.py", line 143, in __init__
    graph = ChainGraph(fst, log_domain=True)
  File "/home/textmining/Goodarzi/pychain_example/tools/pychain/graph.py", line 70, in __init__
    raise Exception("An empty graph encountered!")
Exception: An empty graph encountered!
```

I would be thankful if you help me with this.

**Comment by YiwenShaoStephen** [comment]
Thanks for the feedback! I checked the last commit in PyChain and found that the [new added line](https://github.com/YiwenShaoStephen/pychain/blob/master/pychain/graph.py#L69) caused the issue. 
An empty graph will happen when you compose your numerator FST with the denominator FST but got an empty one. It should rarely happen in the training set due to the pruning we did in preparing denominator FST but will be more likely to happen in valid set or test set (valid set in your case).
For now, you can either delete this line [https://github.com/YiwenShaoStephen/pychain/blob/master/pychain/graph.py#L69](url) (it will be safe as I've already skipped empty graph [here](https://github.com/YiwenShaoStephen/pychain_example/blob/master/dataset.py#L145)), or include your valid set in your denominator preparation part. I'll deal with this issue in pychain soon.
Also, I'm going to upload the mini_librispeech example soon and hopefully it will also be helpful.

**Comment by mohsen-goodarzi** [comment]
I commented out the exception line (https://github.com/YiwenShaoStephen/pychain/blob/master/pychain/graph.py#L69)
and it is working now.
Thank you so much.
